# Generated by Django 3.1.8 on 2022-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220320_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
