# Generated by Django 3.1.8 on 2022-03-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=50)),
                ('pan', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('loan', models.TextField(max_length=50)),
                ('loanamount', models.IntegerField()),
                ('loanlength', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
